State and prove the universal property of the free magma quotiented by a theory.
teorth/equational_theories pull request #563
Opened 2024-10-13 22:09 UTC by codyroux

2024-10-13 22:29 UTC, pitmonticone requested changes

2024-10-13 22:29 UTC, pitmonticone commented on equational_theories/Completeness.lean
> +#print satisfiesPhi
Can you remove these `#check` and `#print`.

2024-10-13 22:29 UTC, pitmonticone commented on equational_theories/Completeness.lean
> +  simp [HasEquiv.Equiv, SetoidOfLaws, RelOfLaws]
This non-terminal `simp` should be avoided. Please use the `simp only` output of `simp?`.

2024-10-13 22:29 UTC, pitmonticone commented on equational_theories/Completeness.lean
> +  exact fun α β f g a x ↦ congrFun a x
Please commit this suggestion:

```suggestion
lemma eq_app : ∀ α β (f g : α → β), f = g → ∀ x, f x = g x := fun α β f g a x ↦ congrFun a x
```

2024-10-13 23:15 UTC, merged

2024-10-14 00:01 UTC, codyroux commented
Thanks Pietro!

2024-10-14 00:57 UTC, pitmonticone commented
Thank you @codyroux for your contribution!